name: Package Source Code

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create temporary directory
      run: mkdir temp

    - name: Move repository to temporary directory
      run: |
        repo_name=$(basename "$GITHUB_REPOSITORY")
        mkdir temp/$repo_name
        shopt -s extglob
        cp -r !(temp) temp/$repo_name

    - name: Create tar.gz package
      run: |
        repo_name=$(basename "$GITHUB_REPOSITORY")
        tar -czvf temp/clashforshell.tar.gz -C temp $repo_name

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: clashforshell-source-code
        path: temp/clashforshell.tar.gz
