name: Package Source Code

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create tar.gz package
      run: tar --exclude='./.git' --exclude='./.github' --exclude='./.gitignore' --exclude='./.gitattributes' -czvf clashforshell.tar.gz .
      
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: clashforshell-source-code
        path: clashforshell.tar.gz
