name: Package Source Code

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create temporary directory
      run: mkdir -p /tmp/clashforshell

    - name: Copy files to temporary directory
      run: |
        shopt -s extglob dotglob
        cp -r !(.|.git|.github|.gitignore|.gitattributes) /tmp/clashforshell

    - name: Create tar.gz package
      run: |
        cd /tmp/clashforshell
        tar -czvf clashforshell.tar.gz .
        mv clashforshell.tar.gz $GITHUB_WORKSPACE

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: clashforshell-source-code
        path: clashforshell.tar.gz