name: Package Source Code

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create temporary directory
      run: mkdir temp

    - name: Create tar.gz package
      run: |
        tar --exclude='./.git' --exclude='./.github' --exclude='./.gitignore' --exclude='./.gitattributes' --exclude='./temp' -czvf temp/clashforshell.tar.gz .

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: clashforshell
        path: temp/clashforshell.tar.gz
